language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_7c61f7d7bb76_key -iv $encrypted_7c61f7d7bb76_iv
    -in secring.gpg.enc -out secring.gpg -d;
  fi
- rm -rf $HOME/.ivy2/cache/scala_2.10/sbt_0.13/com.47deg/sbt-org-policies
script:
- sbt ++$TRAVIS_SCALA_VERSION clean compile test
- sbt ++$TRAVIS_SCALA_VERSION publishLocal;
- if [ "$TRAVIS_BRANCH" = "master" ]; then
    sbt ++$TRAVIS_SCALA_VERSION scripted;
  fi
after_success:
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess
- cd autocheck && sbt -Dplugin.version=$(cat ../version.sbt | sed 's/.*"\(.*\)".*/\1/') checkDependencies
