language: scala
scala:
- 2.10.6
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
before_install:
- openssl aes-256-cbc -K $encrypted_7c61f7d7bb76_key -iv $encrypted_7c61f7d7bb76_iv
  -in secring.gpg.enc -out secring.gpg -d
- rm -rf $HOME/.ivy2/cache/scala_2.10/sbt_0.13/com.47deg/sbt-org-policies
script:
- sbt ++$TRAVIS_SCALA_VERSION clean compile test
- sbt ++2.11.8 org-policies-auto-dep-check/compile
- if [ "$TRAVIS_BRANCH" = "master" ]; then
    sbt ++$TRAVIS_SCALA_VERSION publishLocal;
    sbt ++$TRAVIS_SCALA_VERSION scripted;
  fi
after_success:
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess