language: scala

matrix:
  include:
    - scala: 2.12.3
      jdk: oraclejdk8
      env:
        - SBT_VERSION=1.0.1
    - scala: 2.10.6
      jdk: oraclejdk8
      env:
        - SBT_VERSION=0.13.16

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      openssl aes-256-cbc -K $encrypted_7c61f7d7bb76_key -iv $encrypted_7c61f7d7bb76_iv
      -in secring.gpg.enc -out secring.gpg -d;
    fi
  - rm -rf $HOME/.ivy2/cache/scala_2.11/sbt_0.13/com.47deg/sbt-org-policies

script:
  - sbt ^^$SBT_VERSION clean compile test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      sbt ^^$SBT_VERSION scripted;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if grep -q "SNAPSHOT" version.sbt; then
        sbt ^^$SBT_VERSION publish;
      else
        if [ "$SBT_VERSION" = "1.0.1" ]; then
          sbt ^^$SBT_VERSION orgUpdateDocFiles;
          git reset --hard HEAD;
          git clean -f;
          git checkout master;
          git pull origin master;
          sbt ^^$SBT_VERSION release;
        fi
      fi
    fi
  - sbt ^^$SBT_VERSION publishLocal
  - cd autocheck && sbt ^^$SBT_VERSION -Dplugin.version=$(cat ../version.sbt | sed 's/.*"\(.*\)".*/\1/') checkDependencies

cache:
  directories:
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
